enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.1.cjs

packageExtensions:
  # We provide @fortawesome icons through our own @ant-design/icons package
  # (that we define through the "resolutions" field in package.json).
  # Here we tell Yarn that these are in fact peer dependencies of antd now.
  antd@*:
    peerDependencies:
      "@fortawesome/fontawesome-svg-core": "^6.4.0"
      "@fortawesome/free-brands-svg-icons": "^6.4.0"
      "@fortawesome/free-regular-svg-icons": "^6.4.0"
      "@fortawesome/free-solid-svg-icons": "^6.4.0"
      "react-fontawesome-svg-icon": "^1.1.2"

logFilters:
  # Ignore @code-expert/eslint-config warnings – we will integrate this differently in the future
  - pattern: "@code-expert/eslint-config* doesn't provide *, requested by *"
    level: "discard"
  # fp-ts-laws works with fp-ts 3.x
  - pattern: "@code-expert/sync@workspace:. provides fast-check (*) with version 3.*, which doesn't satisfy what fp-ts-laws requests"
    level: "discard"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"
