/* eslint-disable storybook/default-exports */
import { Table, Typography } from 'antd';
import React from 'react';

import { getColumnSearchPropsAcc } from '../../components/TableSearchFilter';
import Icon, { IconName, iconNames } from './Icon';

export default {
  title: 'Foundation/Icons/Icon',
};

const comments: Record<IconName, string> = {
  'angle-down': 'dropdown, select (use with text)',
  'angle-right': 'dropdown, select (use with text)',
  'chart-bar': 'charts',
  'ellipsis-v': 'menu',
  'file-export': 'export to file',
  'info-circle': 'show additional info',
  lightbulb: 'solution',
  'paper-plane-solid': 'indicator to send a email to someone',
  pen: 'edit',
  'save-solid': 'save',
  section: 'use for terms of use',
  'shield-halved': 'show for infos about data protection',
  table: 'table',
  undo: 'cancel, undo',
  xmark: 'close, dismiss',
  'align-justify': 'indicator for editor',
  'bell-slash': 'Disable notifications',
  'book-open': 'Indicator for solution',
  'book-reader': 'Read-only indicator',
  'calendar-check': 'Indicator that subscription is open',
  'caret-down': 'Indicator to show more',
  'caret-left': 'Go to previous student review',
  'caret-right': 'Go to next student review',
  'caret-square-up': 'Indicator if environment has been replaced',
  'caret-up': 'Indicator to show less',
  'chalkboard-teacher': 'Staff indicator',
  'check-square': 'Indicator for done presentation task',
  'chevron-down': 'dropdown, select (use with buttons or menus)',
  'chevron-left': 'Go to previous',
  'chevron-right': 'Go to next',
  'circle-check': 'Success indicator',
  'clipboard-check': 'Indicator for dispensed task',
  'cloud-download-alt': 'Download backup',
  'code-branch': 'Version number indicator',
  'dot-circle': 'Indicator for todo tasks',
  edit: 'Indicator for edit operations',
  'ellipsis-h': 'TODO think about better icons for current usage',
  'envelope-open': 'Indicator for read messages',
  'envelope-regular': 'Indicator for unread messages',
  'envelope-solid': 'Menu item for messages',
  'exclamation-triangle': 'Indicator for warnings',
  'external-link-alt': 'Link task indicator',
  'eye-slash': 'Indicator for not visible content',
  eye: 'Indicator for visible content',
  'file-alt': 'Indicator default selected file',
  'file-download': 'Download file',
  'file-import': 'Import from file',
  'file-signature': 'Indicator if file has changed',
  'folder-open-regular': 'Open folder in project tree',
  'folder-regular': 'Closed Folder in project tree',
  'folder-solid': 'IDE File tap indicator',
  'graduation-cap': 'Indicator for student submission', // only used once
  'lock-open': 'Unlocked group',
  'mars-and-venus': 'Gender indicator',
  'minus-square': 'Close indicator for floating cxPanel',
  'note-sticky': 'Add a note to a student',
  'note-sticky-solid': 'Indicator that a note was added to a student',
  'paper-plane-regular': 'Indicator for invitations',
  'pencil-ruler': 'Indicator for exam preparation',
  'puzzle-piece': 'Moodle integration indicator',
  'question-circle': 'Indicator to show additional information',
  'save-regular': 'Autosave indicator',
  'shield-alt': 'Menu indicator for user check or security settings',
  'sign-in-alt': 'Exercise XP show required xp',
  'sign-out-alt': 'Logout and exercise XP show if required XP have been achieved',
  'sort-numeric-down': 'Sort numbers down',
  'sort-numeric-up-alt': 'Sort numbers up',
  'tachometer-alt': 'Indicator for analytics measurement',
  'times-circle': 'Clear or delete indicator',
  'toggle-off': 'Toggle off',
  'toggle-on': 'Toggle on',
  'trash-arrow-up': 'Restore deleted snapshot',
  'user-check': 'Indicator if user was reviewed',
  'user-clock': 'Online users indicator',
  'user-friends': 'Groups indicator',
  'user-gear': 'Manage users or user settings',
  'user-graduate': 'Student role indicator',
  'user-lock': 'Block user',
  'user-secret': 'Impersonate user',
  'user-shield': 'Admin role indicator',
  user: 'User indicator',
  'users-gear': 'Multiple user indicator or manage user indicator',
  'vector-square': 'Shared runner indicator',
  'window-restore': 'Detach floating cx panel',
  archive: 'Create Backup or archived environment',
  ban: 'Not submitted indicator',
  bars: 'Draggable indicator',
  bell: 'Notifications indicator',
  book: 'Courses indicator',
  boxes: 'Export submissions for task',
  bug: 'LTI debug mode',
  bullhorn: 'Messages or Notifications menu item',
  calendar: 'Presentation calendar indicator',
  check: 'Task solved',
  circle: 'Preliminary results indicator',
  'clock-regular': 'Late submission indicator',
  'clock-solid': 'Late submission indicator',
  code: 'Code task indicator',
  cog: 'Compiling indicator',
  cogs: 'Compile indicator',
  columns: 'indicator for markdown editor with code and preview',
  comment: 'Presentation called indicator',
  comments: 'Review',
  copy: 'Copy',
  database: 'Binary backup',
  desktop: 'E.Tutorial Task',
  docker: 'Environments menu entry',
  eraser: 'Revert dispense of student',
  file: 'Add file',
  flask: 'Test action',
  forward: 'Skipped test indicator',
  frown: 'Presentation task negative student feedback',
  genderless: 'No gender indicator',
  hdd: 'Disk usage',
  heartbeat: 'Status of runner',
  highlighter: 'Regrade menu entry',
  history: 'History panel',
  home: 'Go Home button',
  hotel: 'Switch other organisations',
  html5: 'Html Panel ide',
  image: 'Preview of MD editor',
  inbox: 'Message inbox',
  key: 'LTI consumer secret',
  link: 'Link task indicator',
  list: 'Courses overview',
  lock: 'locked group or read only file indicator',
  mars: 'male indicator',
  meh: 'Presentation task ok student feedback',
  microchip: 'Dedicated runner indicator',
  minus: 'Group decrease size',
  moon: 'dark mode',
  percent: 'Proportial grading',
  play: 'Start job action',
  plus: 'Group increase size',
  print: 'Print view',
  redo: 'Regenerate value',
  running: 'Job running indicator',
  school: 'Switch uas organisations',
  search: 'Search indicator',
  share: 'Import tasks or exercises indicator',
  slideshare: 'Presentation task',
  smile: 'Presentation task good student feedback',
  snowman: 'User icon during winter :)',
  sort: 'Sort',
  spa: 'All appointments done indicator',
  spinner: 'Queued job indicator',
  stop: 'Stop job indicator',
  sun: 'light mode',
  sync: 'Update environments',
  tasks: 'Exercises indicator',
  terminal: 'IDE Terminal tap indicator',
  thumbtack: 'Default selected file',
  times: 'Project publication status',
  tractor: 'Runner indicator',
  trash: 'Delete indicator',
  university: 'Switch universities organisations',
  unlink: 'Absent student indicator',
  unlock: 'Unlock group indicator',
  upload: 'Upload indicator',
  users: 'Indicator for users',
  venus: 'female indicator',
  video: 'Remote presentation indicator',
};

export const All = () => (
  <Table
    bordered={true}
    pagination={false}
    style={{ paddingBottom: '1em' }}
    rowKey={'name'}
    columns={[
      { title: 'Icon', dataIndex: 'icon', width: 70 },
      {
        title: 'Name',
        dataIndex: 'name',
        render: (_, { name }) => (
          <Typography.Text copyable={{ text: `<Icon name="${name}" />` }}>{name}</Typography.Text>
        ),
      },
      {
        title: 'When to use',
        dataIndex: 'comments',
        ...getColumnSearchPropsAcc<{ name: string; comments: string }>(
          'Keyword',
          ({ name, comments }) => `${name} ${comments}`,
        ),
      },
    ]}
    dataSource={iconNames.map((name) => ({
      name,
      icon: <Icon name={name} />,
      comments: comments[name],
    }))}
  />
);
