name: CI:Web

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=4096"
  VITEST_SEGFAULT_RETRY: 3

jobs:
  web-lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn' # Set this to npm, yarn or pnpm.
      - name: Install app dependencies and build web
        run: yarn && yarn build
      - name: Prettier
        run: yarn lint:format
      - name: Lint
        run: yarn lint:static
  web-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn' # Set this to npm, yarn or pnpm.
      - name: Install app dependencies and build web
        run: yarn && yarn build
      - name: Typecheck
        run: yarn lint:ts
  web-test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn' # Set this to npm, yarn or pnpm.
      - name: Install app dependencies and build web
        run: yarn && yarn build
      - name: Test
        run: yarn test:unit
